version: '3.8'
services:
  frontend:
    image: 
      ${DOCKERHUB_USERNAME}/3nigma-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_DOCKER_ENV=true
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: 
      ${DOCKERHUB_USERNAME}/3nigma-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://db:27017/enigma
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: ["mongod", "--bind_ip_all", "--quiet", "--logpath", "/dev/null"]
    environment:
      - MONGODB_INITDB_DATABASE=enigma
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge