services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_GRAPHQL_URI=${VITE_GRAPHQL_URI}
      - VITE_DOCKER_ENV=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_LOG_LEVEL=warning
      - MONGO_INITDB_QUIET=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge