name: CI

on:
  push:
    branches:
      - docker-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "VITE_API_URL=http://backend:3001" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKER_USERNAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker-compose build
          docker-compose push
