name: CI

on:
  push:
    branches:
      - docker-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/3nigma-frontend:latest ./client
          docker push ${{ vars.DOCKERHUB_USERNAME }}/3nigma-frontend:latest
          with:
            build-args:
              VITE_GRAPHQL_URI=${{ secrets.VITE_GRAPHQL_URI }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/3nigma-backend:latest ./server
          docker push ${{ vars.DOCKERHUB_USERNAME }}/3nigma-backend:latest
