name: Docker Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.client.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/3nigma-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile.server
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/3nigma-backend:latest
